BitGo/bitgo-utxo-lib

- package.json
- src/ecpair.js
- test/ecpair.js
This is a non invasive change to add a method to deal with private keys smaller than 32 bytes. If we change the d.get method directly or toHex(), we would roll out this change without any ability to measure it's impact.
> Add a method to pad addresses smaller than 32 bytes

- src/networks.js
`btg` is the prefix defined by [slip-0173](https://github.com/satoshilabs/slips/blob/master/slip-0173.md) and used in [the official bitcoinjs-lib fork](https://github.com/BTCGPU/bitcoinjs-lib/blob/master/src/networks.js#L7)
> add a bech32 prefix for bitcoin gold

- package.json
Signed-off-by: Tyler Levine <tyler@bitgo.com>
> BG-7253: Upgrade bitgo-utxo-lib version to 1.1.2

- package.json
- src/ecpair.js
- src/fastcurve.js
- src/hdnode.js
- src/transaction_builder.js
- test/ecpair.js
- test/hdnode.js
- test/integration/cltv.js
- test/integration/transactions.js
There are a few functions in BitGoJS `src/bitcoin.js` which depend on secp256k1 for acceleration of elliptic curve operations. These are low-level functions which really belong in bitgo-utxo-lib.
Signed-off-by: Tyler Levine <tyler@bitgo.com>
> BG-8888: Move secp256k1 dependent functions from bitgojs

- src/ecpair.js
- src/hdnode.js
- test/ecpair.js
* If fastcurve returns a falsey value (for example, if it determines
that a signature is invalid and returns false from verify), it will be
treated as though the fast path is not available, and will attempt to
re-verify using the slow path.
Signed-off-by: Tyler Levine <tyler@bitgo.com>
> BG-8910: Fix issue with falsey return values from fastcurve

- src/crypto.js
Electron switched from openSSL to boringSSL and forgot to implement `ripemd160` and when they did, they ignored the short alias `rmd160`: https://github.com/electron/electron/pull/16572
If the current environment does not support `rmd160` but supports `ripemd160`, we now use that one. If it doesn't support either, it will still die with `Digest method not supported`
> BG-10188 use ripemd160 if rmd160 is not supported

- package.json
- New feature: LTC network statics
- Version 1.4.1 because tag 1.4.0 got used previously on this repo
> Bump version to 1.4.1

- src/transaction.js
- src/transaction_builder.js
- test/fixtures/transaction.json
- test/transaction.js
In #39 Dash special tx support was added. However,
TransactionBuilder is used to sign txes. This commit adds support
for Dash special txes in TransactionBuilder. It also fixes a bug
in the Dash special tx serialization.
> Add Dash special txes to TransactionBuilder

- package.json
- src/networks.js
[BLOCK-214](https://bitgoinc.atlassian.net/browse/BLOCK-214) New branch id id `0x2BB40E60`:
https://github.com/zcash/zips/blob/master/zip-0206.rst
> Update Zcash mainnet network params due to Blossom upgrade

- package.json
JIRA Ticket: [BLOCK-228](https://bitgoinc.atlassian.net/browse/BLOCK-228)
Updated version to "1.7.0-rc.0" for publishing to npmjs and testing internal components without affecting external community.
When prime time, Tue 12/10/19 - Wed 12/11/19, we'll then update to the official "1.7.0" release version.
> BLOCK-228 Updated version to "1.7.0-rc.0" for publishing to npmjs and testing internal components.

- src/networks.js
Bitcoin Cash, Bitcoin SV, and Zcash never activated the segwit softfork
and support neither the bech32 address format nor witness programs.
Issue: BLOCK-223
> Remove bech32 prefixes from non-segwit coins

- package-lock.json
- package.json
Fixes 7 vulnerabilities. Package now has a clean audit.
The vulnerabilities were a bit theoretical since `nyc` is only used
when testing.
Issue: BLOCK-252
> Update `nyc` fix npm audit

- .travis.yml
- test/forks/btg/transaction_builder.js
- test/integration/addresses.js
One of the tests calls out to `blockchain.info` to an extent that we get
rate limited by Cloudflare.
The decrease in test coverage is justified by having a meaningful CI result
again.
Issue: BLOCK-253
Other Changes:
1a910f9
Make code pass `standard` linter
Due to alert fatigue this was missed earlier
> Skip failing integration test

- package.json
- test/forks/btg/transaction_builder.js
Since `coverage` only runs mocha, which does not run tests recursively
by default, the coverage dropped below 90%. This change barely moves
it above 90% again.
Issue: BLOCK-251
> Actually run tests in test/forks/

- src/bitgo/index.js
- src/bitgo/keyutil.js
- src/ecpair.js
- src/index.js
- test/bitgo/keyutil.js
- test/ecpair.js
Move custom key conversion methods to subdir.
This makes the `ECPair` class more compatible with upstream and
reduces conflicts when merging upstream changes.
Issue: BLOCK-261
> Add src/bitgo/keyutil

- src/ecpair.js
- src/networks.js
- test/ecpair.js
fe30012
src/networks.js: reorder networks
Order networks alphabetically.
The test `ecpair.js` is modified so that the `NETWORKS_LIST` still has
`bitcoin` and `testnet` as the final elements.
Remove misleading comments.
Issue: BG-16465
0ec6b0b
src/networks.js: fix references
* Remove confusing / invalid references
* Add links to `validation.cpp`/`chainparams.cpp` for various forks
Issue: BG-16465
> Improve src/networks.js

- src/coins.js
- src/networks.js
- test/networks.js
See individual commits
00d19ce
src/coins.js: add getMainnet/getTestnet
These methods are useful when grouping tests
3e22726
src/coins.js: add isDash to isValidNetwork
99c7060
src/coins.js: isValidCoin -> isValidNetwork
The function takes `network` as an argument after all.
Add deprecation notice for old func.
b75742a
src/networks.js: add tests
Make sure values are distinct unless explicitly grouped.
This method uncovered bug BG-16466.
Issue: BG-16465
06f0b92
src/networks.js: define coin network names
We need to describe some more relationships between networks. For instance,
it is very useful to define `getMainnet(network)` and
`getTestnet(network)`.
These methods would fit well in `coins.js` and can be implemented using
object equality on the constants defined in `network.js`. However, …
> Add tests for networks, describe bugs

- CHANGELOG.md
Remove original content: Since we are using a different versioning
scheme to upstream bitcoinjs-lib, it is confusing to have a Changelog
which doesn't fit our version numbers. Describe custom version scheme
and link to pre-fork changelog instead.
Start new Changelog with changes relevant to this repository instead.
Issue: BG-16924
> Replace CHANGELOG.md

- package.json
- src/bufferutils.js
- src/transaction.js
- test/bufferutils.js
- test/fixtures/bufferutils.json
They are not needed and are already removed upstream.
> Remove outdated and unused bufferutils

- src/forks/zcash/bufferutils.js
- src/forks/zcash/version.js
- src/transaction.js
Increases readability of `src/transaction.js` and reduces difference
to upstream.
Issue: BG-16466
> refactor(zcash): move read/write to bufferutils

- package.json
- src/transaction_builder.js
see https://github.com/BitGo/bitgo-utxo-lib/pull/89#discussion_r506369556
It should be OK to call this method even if a TX already has
a signature. (Re-)setting the value does not alter the TX message
digest and so it does not invalidate any existing signatures (the way
changing the TX's `locktime` would). The caller of course must be
sure to only set the consensusBranchId that is valid for the current
network, and there is only one valid option per network.
Removing this check is required in downstream settings where an
application uses this library to add multiple signatures to a
multisig input and needs to overide the default consensusBranchId
each time.
TICKET BG-24753
> Bg 24753 remove branch id check
